---
- name: wkhtmltopdf | check if binary is present
  find:
    paths: 
      - /usr/bin
      - /usr/local/bin
    patterns: wkhtmltopdf
    recurse: yes
  register: wkhtmltopdf_find

- name: wkhtmltopdf | install package
  block:

    - name: wkhtmltopdf | install remaining dependencies
      become: yes
      shell: 
        cmd: apt-get install wkhtmltopdf=0.12.5-1 -y
        warn: no

  when: wkhtmltopdf_find.matched == 0

